apiVersion: v1
kind: Service
metadata:
  name: student-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: student-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
